Repository nextcloud/officeonline, pull requests merged in 2024-12, with the labels that each got.

#605 style: Fix php-cs issues
  .github/workflows/lint-php-cs.yml
  lib/AppConfig.php
  lib/Controller/DocumentController.php
  lib/Controller/FederationController.php
  lib/Controller/SettingsController.php
  lib/Controller/WopiController.php
  lib/Db/DirectMapper.php
  lib/Helper.php
  lib/Middleware/WOPIMiddleware.php
  lib/Preview/Office.php
  lib/Service/FederationService.php
  lib/Service/UserScopeService.php
  lib/Settings/Admin.php
  lib/WOPI/DiscoveryManager.php
  lib/WOPI/Parser.php
  tests/bootstrap.php
  tests/features/bootstrap/FeatureContext.php
Labels: 3. to review, technical debt

#604 fix: Proper default value for to make mode parameter optional
  lib/Controller/TemplatesController.php
Labels: 3. to review, bug

#606 chore: Switch to new API to set volatile user to prevent persisting it in any case
  lib/Controller/WopiController.php
  lib/Service/UserScopeService.php
Labels: 3. to review, bug

#607 fix: Always lookup lower case file extensions
  lib/WOPI/Parser.php
Labels: 3. to review, bug

#608 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
