Repository nextcloud/officeonline, pull requests merged in 2024-03, with the labels that each got.

#523 Fixed remote redirect URL for federation shared files
  lib/Service/FederationService.php
Labels: 4. to release, bug, feedback-requested

#526 Fix broken calls for inline script support
  lib/AppInfo/Application.php
  lib/Controller/DocumentController.php
  lib/DirectEditing/DirectEditor.php
Labels: 3. to review, bug

#528 Fix wrong language in new file menu
  lib/AppInfo/Application.php
Labels: feedback-requested
